#!/usr/bin/env python3
"""OKF index regenerator.

Rebuilds the generated catalog table in an OKF bundle's index.md from the
frontmatter of every concept file in concepts/. Only the content between the
markers below is replaced; anything outside them (prose, notes) is preserved.

    <!-- OKF:INDEX:BEGIN ... -->
    ...generated table...
    <!-- OKF:INDEX:END -->

Usage:
    python3 reindex.py [bundle-path]       # default: current directory

Dependencies: Python 3.8+ standard library only. PyYAML is used when available,
with a built-in fallback parser for the OKF frontmatter subset.
"""
from __future__ import annotations

import os
import sys

BEGIN = "<!-- OKF:INDEX:BEGIN (generated by /okf:reindex — do not edit by hand) -->"
END = "<!-- OKF:INDEX:END -->"


def _coerce(val: str):
    val = val.strip()
    if len(val) >= 2 and val[0] in "\"'" and val[-1] == val[0]:
        return val[1:-1]
    if val.startswith("[") and val.endswith("]"):
        inner = val[1:-1].strip()
        return [_coerce(x) for x in inner.split(",")] if inner else []
    return val


def _fallback_parse(block: str) -> dict:
    data: dict = {}
    lines = block.split("\n")
    i, n = 0, len(lines)
    while i < n:
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if not line[0].isspace() and ":" in line:
            key, _, rest = line.partition(":")
            key, rest = key.strip(), rest.strip()
            if rest:
                data[key] = _coerce(rest)
                i += 1
                continue
            items: list = []
            i += 1
            while i < n and (not lines[i].strip() or lines[i][0].isspace()):
                cur = lines[i]
                if not cur.strip():
                    i += 1
                    continue
                stripped = cur.strip()
                if stripped.startswith("- "):
                    item = stripped[2:].strip()
                    if ":" in item and not item.startswith("["):
                        k2, _, v2 = item.partition(":")
                        items.append({k2.strip(): _coerce(v2)})
                    else:
                        items.append(_coerce(item))
                i += 1
            data[key] = items
        else:
            i += 1
    return data


def parse_frontmatter(text: str) -> dict | None:
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    block = text[3:end].strip("\n")
    try:
        import yaml  # type: ignore

        data = yaml.safe_load(block)
        return data if isinstance(data, dict) else {}
    except Exception:
        return _fallback_parse(block)


def _fmt_tags(value) -> str:
    if not value:
        return ""
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value)


def collect_concepts(concepts_dir: str) -> list[dict]:
    rows = []
    if not os.path.isdir(concepts_dir):
        return rows
    for fname in sorted(f for f in os.listdir(concepts_dir) if f.endswith(".md")):
        path = os.path.join(concepts_dir, fname)
        try:
            with open(path, "r", encoding="utf-8") as fh:
                fm = parse_frontmatter(fh.read())
        except OSError:
            fm = None
        if not fm:
            continue
        rows.append(
            {
                "id": str(fm.get("id") or fname[:-3]),
                "title": str(fm.get("title") or ""),
                "type": str(fm.get("type") or ""),
                "status": str(fm.get("status") or ""),
                "updated": str(fm.get("updated") or ""),
                "tags": _fmt_tags(fm.get("tags")),
                "file": f"concepts/{fname}",
            }
        )
    rows.sort(key=lambda r: (r["type"], r["id"]))
    return rows


def build_table(rows: list[dict]) -> str:
    lines = [
        BEGIN,
        "",
        f"_Generated: {len(rows)} concept(s)._",
        "",
        "| ID | Title | Type | Status | Updated | Tags |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        link = f"[`{r['id']}`]({r['file']})"
        lines.append(
            f"| {link} | {r['title']} | {r['type']} | {r['status']} "
            f"| {r['updated']} | {r['tags']} |"
        )
    if not rows:
        lines.append("| _(no concepts yet)_ |  |  |  |  |  |")
    lines += ["", END]
    return "\n".join(lines)


def splice(existing: str, table: str) -> str:
    if BEGIN in existing and END in existing:
        head = existing[: existing.index(BEGIN)]
        tail = existing[existing.index(END) + len(END) :]
        return f"{head}{table}{tail}"
    if existing.strip():
        return f"{existing.rstrip()}\n\n{table}\n"
    return f"# Index\n\n{table}\n"


def main(argv: list[str]) -> int:
    bundle = (argv[1] if len(argv) > 1 and argv[1].strip() else ".").strip()
    bundle = os.path.abspath(os.path.expanduser(bundle))
    if not os.path.isdir(bundle):
        print(f"OKF: bundle path is not a directory: {bundle}", file=sys.stderr)
        return 2

    rows = collect_concepts(os.path.join(bundle, "concepts"))
    index_path = os.path.join(bundle, "index.md")
    existing = ""
    if os.path.isfile(index_path):
        with open(index_path, "r", encoding="utf-8") as fh:
            existing = fh.read()

    new_content = splice(existing, build_table(rows))
    with open(index_path, "w", encoding="utf-8") as fh:
        fh.write(new_content)

    print(f"OKF reindex — wrote {index_path}")
    print(f"Indexed {len(rows)} concept(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
