#!/usr/bin/env python3
"""OKF index regenerator + link-graph generator.

Two responsibilities:
  1. Regenerate the `links:` frontmatter of every concept from its body
     `[[id]]` wiki-links (surgical splice; skip-if-unchanged).
  2. Rebuild the generated table in index.md.

Usage:
    python3 reindex.py [bundle-path] [--dry-run]

Python 3.8+ stdlib only.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import okf_common as oc  # noqa: E402

BEGIN = "<!-- OKF:INDEX:BEGIN (generated by /okf:reindex — do not edit by hand) -->"
END = "<!-- OKF:INDEX:END -->"


def _fmt_tags(value) -> str:
    if not value:
        return ""
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value)


def collect_concepts(concepts_dir: str) -> list:
    rows = []
    if not os.path.isdir(concepts_dir):
        return rows
    for fname in sorted(f for f in os.listdir(concepts_dir) if f.endswith(".md")):
        path = os.path.join(concepts_dir, fname)
        try:
            with open(path, "r", encoding="utf-8") as fh:
                fm = oc.parse_frontmatter(fh.read())
        except OSError:
            fm = None
        if not fm:
            continue
        rows.append({
            "id": str(fm.get("id") or fname[:-3]),
            "title": str(fm.get("title") or ""),
            "type": str(fm.get("type") or ""),
            "status": str(fm.get("status") or ""),
            "updated": str(fm.get("updated") or ""),
            "tags": _fmt_tags(fm.get("tags")),
            "file": f"concepts/{fname}",
        })
    rows.sort(key=lambda r: (r["type"], r["id"]))
    return rows


def build_table(rows: list) -> str:
    lines = [BEGIN, "", f"_Generated: {len(rows)} concept(s)._", "",
             "| ID | Title | Type | Status | Updated | Tags |",
             "| --- | --- | --- | --- | --- | --- |"]
    for r in rows:
        link = f"[`{r['id']}`]({r['file']})"
        lines.append(f"| {link} | {r['title']} | {r['type']} | {r['status']} "
                     f"| {r['updated']} | {r['tags']} |")
    if not rows:
        lines.append("| _(no concepts yet)_ |  |  |  |  |  |")
    lines += ["", END]
    return "\n".join(lines)


def splice_index(existing: str, table: str) -> str:
    if BEGIN in existing and END in existing:
        head = existing[: existing.index(BEGIN)]
        tail = existing[existing.index(END) + len(END):]
        return f"{head}{table}{tail}"
    if existing.strip():
        return f"{existing.rstrip()}\n\n{table}\n"
    return f"# Index\n\n{table}\n"


def _link_id(entry) -> str:
    """Extract a clean string id from a links: entry (dict-form or plain string)."""
    if isinstance(entry, dict):
        return str(entry.get("id", entry))
    return str(entry)


def regenerate_links(bundle: str, dry_run: bool) -> int:
    """Splice each concept's links: from its body. Returns count of files that
    changed (or would change, under dry_run). Prints migration notices."""
    concepts_dir = os.path.join(bundle, "concepts")
    if not os.path.isdir(concepts_dir):
        return 0
    changed = 0
    for fname in sorted(f for f in os.listdir(concepts_dir) if f.endswith(".md")):
        path = os.path.join(concepts_dir, fname)
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        body_links = oc.extract_wikilinks(oc.body_of(text))
        old_fm = oc.parse_frontmatter(text) or {}
        old_links = [_link_id(x) for x in oc._as_list(old_fm.get("links"))]
        dropped = [x for x in old_links if x not in body_links]
        if dropped:
            print(f"concepts/{fname}: dropped non-body links {dropped} "
                  f"— re-add via [[…]] in the body to keep them")
        spliced = oc.splice_links(text, body_links)
        if spliced != text:
            changed += 1
            if not dry_run:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(spliced)
    return changed


def rebuild_index(bundle: str, dry_run: bool = False) -> int:
    """Regenerate the index.md table from current concept files. Returns the row
    count. Split out from run() so rename can rebuild the index AFTER the file
    rename (otherwise rows would point at the old filename)."""
    rows = collect_concepts(os.path.join(bundle, "concepts"))
    index_path = os.path.join(bundle, "index.md")
    existing = ""
    if os.path.isfile(index_path):
        with open(index_path, "r", encoding="utf-8") as fh:
            existing = fh.read()
    new_index = splice_index(existing, build_table(rows))
    if not dry_run:
        with open(index_path, "w", encoding="utf-8") as fh:
            fh.write(new_index)
    return len(rows)


def run(bundle: str, dry_run: bool = False) -> int:
    bundle = os.path.abspath(os.path.expanduser(bundle))
    if not os.path.isdir(bundle):
        print(f"OKF: bundle path is not a directory: {bundle}", file=sys.stderr)
        return 2
    changed = regenerate_links(bundle, dry_run)
    n = rebuild_index(bundle, dry_run)
    if dry_run:
        print(f"OKF reindex --dry-run: {changed} concept file(s) would change; "
              f"index.md would list {n} concept(s). No files written.")
    else:
        print(f"OKF reindex — wrote {os.path.join(bundle, 'index.md')}")
        print(f"Updated links in {changed} concept(s); indexed {n}.")
    return 0


def main(argv: list) -> int:
    args = [a for a in argv[1:] if a.strip()]
    dry_run = "--dry-run" in args
    positional = [a for a in args if not a.startswith("--")]
    bundle = positional[0] if positional else "."
    return run(bundle, dry_run=dry_run)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
